language: node_js
notifications:
  email:
  - bitcodin-js@bitmovin.net
before_install:
- openssl aes-256-cbc -K $encrypted_6f475b1ddedd_key -iv $encrypted_6f475b1ddedd_iv
  -in test/resources/settings.json.enc -out test/resources/settings.json -d
- npm install -g grunt-cli
