language: node_js

notifications:
  email:
    - bitcodin-js@bitmovin.net

before_install:
- openssl aes-256-cbc -K $encrypted_b4f0616205c0_key -iv $encrypted_b4f0616205c0_iv
  -in test/resources/settings.json.enc -out test/resources/settings.json -d
